export const allProducts = [
    {
      id: "SWZ700rn7nNWwWyHpe10",
      category: "whisky",
      name: "Johnnie Walker Red Label 750ml",
      srcUrl: "/images/jw-red.png",
      images: ["/images/jw-red.png", "/images/jw-black.png", "/images/jw-gold.png"],
      price: 28000,
      discount: { amount: 0, percentage: 0 },
      rating: 4.5,
    },
    {
      id: "dKQ92nKm1bEkLPtNxyA1",
      category: "whisky",
      name: "Chivas Regal 12 Años 750ml",
      srcUrl: "/images/chivas.png",
      images: ["/images/chivas.png"],
      price: 32000,
      discount: { amount: 0, percentage: 10 },
      rating: 4.8,
    },
    {
      id: "LKe20NpQpBzYwMfjRzT2",
      category: "vodka",
      name: "Absolut Vodka 700ml",
      srcUrl: "/images/absolut.png",
      images: ["/images/absolut.png"],
      price: 18000,
      discount: { amount: 0, percentage: 0 },
      rating: 4.2,
    },
    {
      id: "JzA74UyqMsLlzXoHbFq3",
      category: "vodka",
      name: "Smirnoff Vodka 750ml",
      srcUrl: "/images/smirnoff.png",
      images: ["/images/smirnoff.png"],
      price: 16000,
      discount: { amount: 0, percentage: 5 },
      rating: 4.0,
    },
    {
      id: "MeN38WdqLsAaXePpTyE4",
      category: "gin",
      name: "Beefeater Gin 750ml",
      srcUrl: "/images/beefeater.png",
      images: ["/images/beefeater.png"],
      price: 19500,
      discount: { amount: 0, percentage: 15 },
      rating: 4.3,
    },
    {
      id: "VzW92QerNzPoKaDnRxF5",
      category: "ron",
      name: "Havana Club Añejo 750ml",
      srcUrl: "/images/havana.png",
      images: ["/images/havana.png"],
      price: 17000,
      discount: { amount: 0, percentage: 0 },
      rating: 4.1,
    },
    {
      id: "RfA02XypKtUwBvZoGjF6",
      category: "ron",
      name: "Bacardi Carta Blanca 750ml",
      srcUrl: "/images/bacardi.png",
      images: ["/images/bacardi.png"],
      price: 16500,
      discount: { amount: 0, percentage: 10 },
      rating: 4.4,
    },
    {
      id: "HxL90RpzMsXvEdDrByG7",
      category: "cerveza",
      name: "Corona Extra 355ml (pack x6)",
      srcUrl: "/images/corona.png",
      images: ["/images/corona.png"],
      price: 10500,
      discount: { amount: 0, percentage: 0 },
      rating: 4.7,
    },
    {
      id: "NpB48TeqGtYkApJvFxH8",
      category: "cerveza",
      name: "Heineken 473ml (pack x6)",
      srcUrl: "/images/heineken.png",
      images: ["/images/heineken.png"],
      price: 11000,
      discount: { amount: 0, percentage: 5 },
      rating: 4.6,
    },
    {
      id: "WfR63EzoQmXcLzTuJyH9",
      category: "vino",
      name: "Trumpeter Malbec 750ml",
      srcUrl: "/images/trumpeter.png",
      images: ["/images/trumpeter.png"],
      price: 8900,
      discount: { amount: 0, percentage: 0 },
      rating: 4.3,
    },
    {
      id: "PtE75VupAbYwXmKqNzI0",
      category: "vino",
      name: "Luigi Bosca Malbec 750ml",
      srcUrl: "/images/luigi.png",
      images: ["/images/luigi.png"],
      price: 15000,
      discount: { amount: 0, percentage: 15 },
      rating: 4.9,
    },
  ];
  